# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/atelier4Constraints.xdc

# Block Designs: bd/atelier4/atelier4.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4 || ORIG_REF_NAME==atelier4} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_axi_vdma_0_0/atelier4_axi_vdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_axi_vdma_0_0 || ORIG_REF_NAME==atelier4_axi_vdma_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_clk_wiz_0_0/atelier4_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_clk_wiz_0_0 || ORIG_REF_NAME==atelier4_clk_wiz_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_proc_sys_reset_0_0/atelier4_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_proc_sys_reset_0_0 || ORIG_REF_NAME==atelier4_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_processing_system7_0_0/atelier4_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_processing_system7_0_0 || ORIG_REF_NAME==atelier4_processing_system7_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_rgb2dvi_0_0/atelier4_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_rgb2dvi_0_0 || ORIG_REF_NAME==atelier4_rgb2dvi_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_smartconnect_0_0/atelier4_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_smartconnect_0_0 || ORIG_REF_NAME==atelier4_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/bd_de31.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_0/bd_de31_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_1/bd_de31_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_2/bd_de31_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_3/bd_de31_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_4/bd_de31_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_5/bd_de31_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_6/bd_de31_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_7/bd_de31_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_8/bd_de31_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_9/bd_de31_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_10/bd_de31_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_11/bd_de31_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_12/bd_de31_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_13/bd_de31_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_14/bd_de31_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_15/bd_de31_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_16/bd_de31_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_17/bd_de31_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_18/bd_de31_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_19/bd_de31_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_20/bd_de31_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_21/bd_de31_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_22/bd_de31_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_23/bd_de31_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_24/bd_de31_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_25/bd_de31_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_26/bd_de31_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_27/bd_de31_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_28/bd_de31_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_29/bd_de31_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_30/bd_de31_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_31/bd_de31_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_32/bd_de31_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_33/bd_de31_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_34/bd_de31_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_35/bd_de31_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_36/bd_de31_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_37/bd_de31_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_38/bd_de31_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_39/bd_de31_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_40/bd_de31_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_41/bd_de31_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_42/bd_de31_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_43/bd_de31_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_44/bd_de31_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_45/bd_de31_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_46/bd_de31_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_47/bd_de31_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_48/bd_de31_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_49/bd_de31_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_50/bd_de31_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_51/bd_de31_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_52/bd_de31_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_53/bd_de31_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_54/bd_de31_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_55/bd_de31_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/atelier4/ip/atelier4_smartconnect_0_1/atelier4_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_smartconnect_0_1 || ORIG_REF_NAME==atelier4_smartconnect_0_1} -quiet] -quiet

# Block Designs: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/bd_1ef0.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_0/bd_1ef0_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_1/bd_1ef0_psr0_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_2/bd_1ef0_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_3/bd_1ef0_psr_aclk1_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_4/bd_1ef0_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_5/bd_1ef0_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_6/bd_1ef0_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_7/bd_1ef0_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_8/bd_1ef0_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_9/bd_1ef0_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_10/bd_1ef0_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_11/bd_1ef0_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_12/bd_1ef0_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_13/bd_1ef0_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_14/bd_1ef0_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_15/bd_1ef0_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_16/bd_1ef0_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_17/bd_1ef0_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_18/bd_1ef0_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_19/bd_1ef0_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_20/bd_1ef0_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_21/bd_1ef0_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_22/bd_1ef0_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_23/bd_1ef0_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_24/bd_1ef0_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_25/bd_1ef0_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_26/bd_1ef0_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_27/bd_1ef0_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_28/bd_1ef0_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/atelier4/ip/atelier4_v_axi4s_vid_out_0_0/atelier4_v_axi4s_vid_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==atelier4_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_v_proc_ss_0_0/atelier4_v_proc_ss_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_v_proc_ss_0_0 || ORIG_REF_NAME==atelier4_v_proc_ss_0_0} -quiet] -quiet

# Block Designs: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/bd_0837.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837 || ORIG_REF_NAME==bd_0837} -quiet] -quiet

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_0/bd_0837_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_smartconnect_0_0 || ORIG_REF_NAME==bd_0837_smartconnect_0_0} -quiet] -quiet

# Block Designs: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/bd_0cc7.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_0/bd_0cc7_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_1/bd_0cc7_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_2/bd_0cc7_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_3/bd_0cc7_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_4/bd_0cc7_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_5/bd_0cc7_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_6/bd_0cc7_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_7/bd_0cc7_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_8/bd_0cc7_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_9/bd_0cc7_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_10/bd_0cc7_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_11/bd_0cc7_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_12/bd_0cc7_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_13/bd_0cc7_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_14/bd_0cc7_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_15/bd_0cc7_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_16/bd_0cc7_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_17/bd_0cc7_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_18/bd_0cc7_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_19/bd_0cc7_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_20/bd_0cc7_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_21/bd_0cc7_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_22/bd_0cc7_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_23/bd_0cc7_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_24/bd_0cc7_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_25/bd_0cc7_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_26/bd_0cc7_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_27/bd_0cc7_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_28/bd_0cc7_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_29/bd_0cc7_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_30/bd_0cc7_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_31/bd_0cc7_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_32/bd_0cc7_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_33/bd_0cc7_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_34/bd_0cc7_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_35/bd_0cc7_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_36/bd_0cc7_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_37/bd_0cc7_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_38/bd_0cc7_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_39/bd_0cc7_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_40/bd_0cc7_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_41/bd_0cc7_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_42/bd_0cc7_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_43/bd_0cc7_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_44/bd_0cc7_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_45/bd_0cc7_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_46/bd_0cc7_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/bd_0837_vsc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_vsc_0 || ORIG_REF_NAME==bd_0837_vsc_0} -quiet] -quiet

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/bd_0837_hsc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_hsc_0 || ORIG_REF_NAME==bd_0837_hsc_0} -quiet] -quiet

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/bd_0837_input_size_set_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_input_size_set_0 || ORIG_REF_NAME==bd_0837_input_size_set_0} -quiet] -quiet

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_4/bd_0837_rst_axis_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_rst_axis_0 || ORIG_REF_NAME==bd_0837_rst_axis_0} -quiet] -quiet

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0837_reset_sel_axis_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_reset_sel_axis_0 || ORIG_REF_NAME==bd_0837_reset_sel_axis_0} -quiet] -quiet

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0837_axis_register_slice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_axis_register_slice_0_0 || ORIG_REF_NAME==bd_0837_axis_register_slice_0_0} -quiet] -quiet

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_7/bd_0837_axis_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_axis_fifo_0 || ORIG_REF_NAME==bd_0837_axis_fifo_0} -quiet] -quiet

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_8/bd_0837_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_xlslice_0_0 || ORIG_REF_NAME==bd_0837_xlslice_0_0} -quiet] -quiet

# IP: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_9/bd_0837_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0837_xlslice_1_0 || ORIG_REF_NAME==bd_0837_xlslice_1_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_v_tc_0_0/atelier4_v_tc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_v_tc_0_0 || ORIG_REF_NAME==atelier4_v_tc_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_pixelDataToVideoStre_0_3/atelier4_pixelDataToVideoStre_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_pixelDataToVideoStre_0_3 || ORIG_REF_NAME==atelier4_pixelDataToVideoStre_0_3} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_mycolorRegister_0_0/atelier4_mycolorRegister_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_mycolorRegister_0_0 || ORIG_REF_NAME==atelier4_mycolorRegister_0_0} -quiet] -quiet

# IP: bd/atelier4/ip/atelier4_testPatternGen2_0_0/atelier4_testPatternGen2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==atelier4_testPatternGen2_0_0 || ORIG_REF_NAME==atelier4_testPatternGen2_0_0} -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_axi_vdma_0_0/atelier4_axi_vdma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_axi_vdma_0_0 || ORIG_REF_NAME==atelier4_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_axi_vdma_0_0/atelier4_axi_vdma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_axi_vdma_0_0 || ORIG_REF_NAME==atelier4_axi_vdma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_axi_vdma_0_0/atelier4_axi_vdma_0_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_clk_wiz_0_0/atelier4_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_clk_wiz_0_0 || ORIG_REF_NAME==atelier4_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_clk_wiz_0_0/atelier4_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_clk_wiz_0_0 || ORIG_REF_NAME==atelier4_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_clk_wiz_0_0/atelier4_clk_wiz_0_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_proc_sys_reset_0_0/atelier4_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_proc_sys_reset_0_0 || ORIG_REF_NAME==atelier4_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_proc_sys_reset_0_0/atelier4_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_proc_sys_reset_0_0 || ORIG_REF_NAME==atelier4_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_processing_system7_0_0/atelier4_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_processing_system7_0_0 || ORIG_REF_NAME==atelier4_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_rgb2dvi_0_0 || ORIG_REF_NAME==atelier4_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_rgb2dvi_0_0 || ORIG_REF_NAME==atelier4_rgb2dvi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_1/bd_de31_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_1/bd_de31_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_2/bd_de31_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_2/bd_de31_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_3/bd_de31_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_3/bd_de31_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_4/bd_de31_arinsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_5/bd_de31_rinsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_6/bd_de31_awinsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_7/bd_de31_winsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_8/bd_de31_binsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_9/bd_de31_aroutsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_10/bd_de31_routsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_11/bd_de31_awoutsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_12/bd_de31_woutsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_13/bd_de31_boutsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_14/bd_de31_arni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_15/bd_de31_rni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_16/bd_de31_awni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_17/bd_de31_wni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_18/bd_de31_bni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_22/bd_de31_s00a2s_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_23/bd_de31_sarn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_24/bd_de31_srn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_25/bd_de31_sawn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_26/bd_de31_swn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_27/bd_de31_sbn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_28/bd_de31_m00s2a_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_29/bd_de31_m00arn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_30/bd_de31_m00rn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_31/bd_de31_m00awn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_32/bd_de31_m00wn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_33/bd_de31_m00bn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_35/bd_de31_m01s2a_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_36/bd_de31_m01arn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_37/bd_de31_m01rn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_38/bd_de31_m01awn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_39/bd_de31_m01wn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_40/bd_de31_m01bn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_42/bd_de31_m02s2a_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_43/bd_de31_m02arn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_44/bd_de31_m02rn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_45/bd_de31_m02awn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_46/bd_de31_m02wn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_47/bd_de31_m02bn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_49/bd_de31_m03s2a_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_50/bd_de31_m03arn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_51/bd_de31_m03rn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_52/bd_de31_m03awn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_53/bd_de31_m03wn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/bd_0/ip/ip_54/bd_de31_m03bn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_0/ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_1/bd_1ef0_psr0_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_1/bd_1ef0_psr0_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_2/bd_1ef0_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_2/bd_1ef0_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_3/bd_1ef0_psr_aclk1_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_3/bd_1ef0_psr_aclk1_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_4/bd_1ef0_arsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_5/bd_1ef0_rsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_6/bd_1ef0_awsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_7/bd_1ef0_wsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_8/bd_1ef0_bsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_12/bd_1ef0_s00a2s_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_13/bd_1ef0_sarn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_14/bd_1ef0_srn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_18/bd_1ef0_s01a2s_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_19/bd_1ef0_sawn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_20/bd_1ef0_swn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_21/bd_1ef0_sbn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_22/bd_1ef0_m00s2a_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_23/bd_1ef0_m00arn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_24/bd_1ef0_m00rn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_25/bd_1ef0_m00awn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_26/bd_1ef0_m00wn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/bd_0/ip/ip_27/bd_1ef0_m00bn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_smartconnect_0_1/ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_axi4s_vid_out_0_0/atelier4_v_axi4s_vid_out_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==atelier4_v_axi4s_vid_out_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_1/bd_0cc7_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_1/bd_0cc7_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_2/bd_0cc7_arinsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_3/bd_0cc7_rinsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_4/bd_0cc7_awinsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_5/bd_0cc7_winsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_6/bd_0cc7_binsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_7/bd_0cc7_aroutsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_8/bd_0cc7_routsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_9/bd_0cc7_awoutsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_10/bd_0cc7_woutsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_11/bd_0cc7_boutsw_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_12/bd_0cc7_arni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_13/bd_0cc7_rni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_14/bd_0cc7_awni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_15/bd_0cc7_wni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_16/bd_0cc7_bni_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_20/bd_0cc7_s00a2s_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_21/bd_0cc7_sarn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_22/bd_0cc7_srn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_23/bd_0cc7_sawn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_24/bd_0cc7_swn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_25/bd_0cc7_sbn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_26/bd_0cc7_m00s2a_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_27/bd_0cc7_m00arn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_28/bd_0cc7_m00rn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_29/bd_0cc7_m00awn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_30/bd_0cc7_m00wn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_31/bd_0cc7_m00bn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_33/bd_0cc7_m01s2a_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_34/bd_0cc7_m01arn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_35/bd_0cc7_m01rn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_36/bd_0cc7_m01awn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_37/bd_0cc7_m01wn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_38/bd_0cc7_m01bn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_40/bd_0cc7_m02s2a_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_41/bd_0cc7_m02arn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_42/bd_0cc7_m02rn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_43/bd_0cc7_m02awn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_44/bd_0cc7_m02wn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_1/ip/ip_45/bd_0cc7_m02bn_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_0/ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_1/bd_0837_vsc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0837_vsc_0 || ORIG_REF_NAME==bd_0837_vsc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_2/bd_0837_hsc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0837_hsc_0 || ORIG_REF_NAME==bd_0837_hsc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_3/bd_0837_input_size_set_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_4/bd_0837_rst_axis_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0837_rst_axis_0 || ORIG_REF_NAME==bd_0837_rst_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_4/bd_0837_rst_axis_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0837_rst_axis_0 || ORIG_REF_NAME==bd_0837_rst_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0837_reset_sel_axis_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0837_reset_sel_axis_0 || ORIG_REF_NAME==bd_0837_reset_sel_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0837_reset_sel_axis_0_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_5/bd_0837_reset_sel_axis_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0837_reset_sel_axis_0 || ORIG_REF_NAME==bd_0837_reset_sel_axis_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/ip/ip_6/bd_0837_axis_register_slice_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0837_axis_register_slice_0_0 || ORIG_REF_NAME==bd_0837_axis_register_slice_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_proc_ss_0_0/bd_0/bd_0837_ooc.xdc

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/ip/atelier4_v_tc_0_0/atelier4_v_tc_0_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==atelier4_v_tc_0_0 || ORIG_REF_NAME==atelier4_v_tc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/travail/s4InfoAtelier4/s4InfoAtelier4.gen/sources_1/bd/atelier4/atelier4_ooc.xdc
